# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Simple App (TV MAZE)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Simple App (TV MAZE)

	pod 'SDWebImageSwiftUI'

end
